# Generated by Django 4.1.4 on 2022-12-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitt',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
