# Generated by Django 4.1.4 on 2022-12-11 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_profile_name_alter_profile_profile_img'),
        ('twittapp', '0002_twitt_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profileapp.profile'),
            preserve_default=False,
        ),
    ]
